package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Admisson generated by hbm2java
 */
@Entity
@Table(name = "Admisson", catalog = "schoolmanagement")
public class Admisson implements java.io.Serializable {

	private int admissonId;
	private Student student;
	private Date dateofAdmisson;
	private String previousInstitute;
	private String reasonForLeave;

	public Admisson() {
	}

	public Admisson(int admissonId) {
		this.admissonId = admissonId;
	}

	public Admisson(int admissonId, Student student, Date dateofAdmisson, String previousInstitute,
			String reasonForLeave) {
		this.admissonId = admissonId;
		this.student = student;
		this.dateofAdmisson = dateofAdmisson;
		this.previousInstitute = previousInstitute;
		this.reasonForLeave = reasonForLeave;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "admissonId", unique = true, nullable = false)
	public int getAdmissonId() {
		return this.admissonId;
	}

	public void setAdmissonId(int admissonId) {
		this.admissonId = admissonId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentId")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateofAdmisson", length = 23)
	public Date getDateofAdmisson() {
		return this.dateofAdmisson;
	}

	public void setDateofAdmisson(Date dateofAdmisson) {
		this.dateofAdmisson = dateofAdmisson;
	}
	@NotEmpty
	@Column(name = "previousInstitute", length = 50)
	public String getPreviousInstitute() {
		return this.previousInstitute;
	}

	public void setPreviousInstitute(String previousInstitute) {
		this.previousInstitute = previousInstitute;
	}
	@NotEmpty
	@Column(name = "reasonForLeave", length = 50)
	public String getReasonForLeave() {
		return this.reasonForLeave;
	}

	public void setReasonForLeave(String reasonForLeave) {
		this.reasonForLeave = reasonForLeave;
	}

}
