package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * ClassStudent generated by hbm2java
 */
@Entity
@Table(name = "ClassStudent", catalog = "schoolmanagement")
public class ClassStudent implements java.io.Serializable {

	private int classId;
	private Grade grade;
	private String nameOfClass;
	private Set<Student> students = new HashSet<Student>(0);

	public ClassStudent() {
	}

	public ClassStudent(int classId) {
		this.classId = classId;
	}

	public ClassStudent(int classId, Grade grade, String nameOfClass, Set<Student> students) {
		this.classId = classId;
		this.grade = grade;
		this.nameOfClass = nameOfClass;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "classId", unique = true, nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gradeId")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}
	@NotEmpty
	@Column(name = "nameOfClass", length = 50)
	public String getNameOfClass() {
		return this.nameOfClass;
	}

	public void setNameOfClass(String nameOfClass) {
		this.nameOfClass = nameOfClass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classStudent")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
