package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DivisonId generated by hbm2java
 */
@Embeddable
public class DivisonId implements java.io.Serializable {

	private int staffId;
	private int subjectsId;

	public DivisonId() {
	}

	public DivisonId(int staffId, int subjectsId) {
		this.staffId = staffId;
		this.subjectsId = subjectsId;
	}

	@Column(name = "staffId", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "subjectsId", nullable = false)
	public int getSubjectsId() {
		return this.subjectsId;
	}

	public void setSubjectsId(int subjectsId) {
		this.subjectsId = subjectsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DivisonId))
			return false;
		DivisonId castOther = (DivisonId) other;

		return (this.getStaffId() == castOther.getStaffId()) && (this.getSubjectsId() == castOther.getSubjectsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStaffId();
		result = 37 * result + this.getSubjectsId();
		return result;
	}

}
