package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Educational generated by hbm2java
 */
@Entity
@Table(name = "Educational", catalog = "schoolmanagement")
public class Educational implements java.io.Serializable {

	private int id;
	private Staff staff;
	private String nameOfUniversityOrInstitute;
	private String yearOfEducation;
	private String degree;
	private String grade;

	public Educational() {
	}

	public Educational(int id) {
		this.id = id;
	}

	public Educational(int id, Staff staff, String nameOfUniversityOrInstitute, String yearOfEducation, String degree,
			String grade) {
		this.id = id;
		this.staff = staff;
		this.nameOfUniversityOrInstitute = nameOfUniversityOrInstitute;
		this.yearOfEducation = yearOfEducation;
		this.degree = degree;
		this.grade = grade;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staffId")
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}
	@NotEmpty
	@Column(name = "nameOfUniversityOrInstitute", length = 50)
	public String getNameOfUniversityOrInstitute() {
		return this.nameOfUniversityOrInstitute;
	}

	public void setNameOfUniversityOrInstitute(String nameOfUniversityOrInstitute) {
		this.nameOfUniversityOrInstitute = nameOfUniversityOrInstitute;
	}
	@NotEmpty
	@Column(name = "yearOfEducation", length = 30)
	public String getYearOfEducation() {
		return this.yearOfEducation;
	}

	public void setYearOfEducation(String yearOfEducation) {
		this.yearOfEducation = yearOfEducation;
	}

	@Column(name = "degree", length = 50)
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "grade", length = 50)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

}
