package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "Grade", catalog = "schoolmanagement")
public class Grade implements java.io.Serializable {

	private int gradeId;
	private String gradeName;
	private Set<ClassStudent> classStudents = new HashSet<ClassStudent>(0);

	public Grade() {
	}

	public Grade(int gradeId) {
		this.gradeId = gradeId;
	}

	public Grade(int gradeId, String gradeName, Set<ClassStudent> classStudents) {
		this.gradeId = gradeId;
		this.gradeName = gradeName;
		this.classStudents = classStudents;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "gradeId", unique = true, nullable = false)
	public int getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(int gradeId) {
		this.gradeId = gradeId;
	}

	@Column(name = "gradeName", length = 50)
	public String getGradeName() {
		return this.gradeName;
	}

	public void setGradeName(String gradeName) {
		this.gradeName = gradeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<ClassStudent> getClassStudents() {
		return this.classStudents;
	}

	public void setClassStudents(Set<ClassStudent> classStudents) {
		this.classStudents = classStudents;
	}

}
