package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MarksId generated by hbm2java
 */
@Embeddable
public class MarksId implements java.io.Serializable {

	private int idOfSubjects;
	private int idOfStudent;

	public MarksId() {
	}

	public MarksId(int idOfSubjects, int idOfStudent) {
		this.idOfSubjects = idOfSubjects;
		this.idOfStudent = idOfStudent;
	}

	@Column(name = "idOfSubjects", nullable = false)
	public int getIdOfSubjects() {
		return this.idOfSubjects;
	}

	public void setIdOfSubjects(int idOfSubjects) {
		this.idOfSubjects = idOfSubjects;
	}

	@Column(name = "idOfStudent", nullable = false)
	public int getIdOfStudent() {
		return this.idOfStudent;
	}

	public void setIdOfStudent(int idOfStudent) {
		this.idOfStudent = idOfStudent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MarksId))
			return false;
		MarksId castOther = (MarksId) other;

		return (this.getIdOfSubjects() == castOther.getIdOfSubjects())
				&& (this.getIdOfStudent() == castOther.getIdOfStudent());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOfSubjects();
		result = 37 * result + this.getIdOfStudent();
		return result;
	}

}
