package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Marks generated by hbm2java
 */
@Entity
@Table(name = "Marks", catalog = "schoolmanagement")
public class Marks implements java.io.Serializable {

	private MarksId id;
	private Student student;
	private Subjects subjects;
	private Double marksSemesterI;
	private Double marksSemesterIi;
	private Double totalMarks;

	public Marks() {
	}

	public Marks(MarksId id, Student student, Subjects subjects) {
		this.id = id;
		this.student = student;
		this.subjects = subjects;
	}

	public Marks(MarksId id, Student student, Subjects subjects, Double marksSemesterI, Double marksSemesterIi,
			Double totalMarks) {
		this.id = id;
		this.student = student;
		this.subjects = subjects;
		this.marksSemesterI = marksSemesterI;
		this.marksSemesterIi = marksSemesterIi;
		this.totalMarks = totalMarks;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOfSubjects", column = @Column(name = "idOfSubjects", nullable = false)),
			@AttributeOverride(name = "idOfStudent", column = @Column(name = "idOfStudent", nullable = false)) })
	public MarksId getId() {
		return this.id;
	}

	public void setId(MarksId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOfStudent", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOfSubjects", nullable = false, insertable = false, updatable = false)
	public Subjects getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Subjects subjects) {
		this.subjects = subjects;
	}
	@NotNull
	@Column(name = "marksSemesterI", precision = 15, scale = 0)
	public Double getMarksSemesterI() {
		return this.marksSemesterI;
	}

	public void setMarksSemesterI(Double marksSemesterI) {
		this.marksSemesterI = marksSemesterI;
	}
	@NotNull
	@Column(name = "marksSemesterII", precision = 15, scale = 0)
	public Double getMarksSemesterIi() {
		return this.marksSemesterIi;
	}

	public void setMarksSemesterIi(Double marksSemesterIi) {
		this.marksSemesterIi = marksSemesterIi;
	}

	@Column(name = "totalMarks", precision = 15, scale = 0)
	public Double getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Double totalMarks) {
		this.totalMarks = totalMarks;
	}

}
