package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * StaffExperience generated by hbm2java
 */
@Entity
@Table(name = "StaffExperience", catalog = "schoolmanagement")
public class StaffExperience implements java.io.Serializable {

	private int id;
	private Staff staff;
	private String nameOfWorkplace;
	private String yearOfWorking;
	private String position;
	private String achievement;

	public StaffExperience() {
	}

	public StaffExperience(int id) {
		this.id = id;
	}

	public StaffExperience(int id, Staff staff, String nameOfWorkplace, String yearOfWorking, String position,
			String achievement) {
		this.id = id;
		this.staff = staff;
		this.nameOfWorkplace = nameOfWorkplace;
		this.yearOfWorking = yearOfWorking;
		this.position = position;
		this.achievement = achievement;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staffId")
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}
	@NotEmpty 
	@Column(name = "nameOfWorkplace", length = 50)
	public String getNameOfWorkplace() {
		return this.nameOfWorkplace;
	}

	public void setNameOfWorkplace(String nameOfWorkplace) {
		this.nameOfWorkplace = nameOfWorkplace;
	}
	@NotEmpty
	@Column(name = "yearOfWorking", length = 30)
	public String getYearOfWorking() {
		return this.yearOfWorking;
	}

	public void setYearOfWorking(String yearOfWorking) {
		this.yearOfWorking = yearOfWorking;
	}
	@Column(name = "position", length = 30)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}
	@NotEmpty
	@Column(name = "achievement", length = 50)
	public String getAchievement() {
		return this.achievement;
	}

	public void setAchievement(String achievement) {
		this.achievement = achievement;
	}

}
