package entities;
// Generated Aug 26, 2016 12:06:24 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name = "Subjects", catalog = "schoolmanagement")
public class Subjects implements java.io.Serializable {

	private int id;
	private String nameOfSubjects;
	private Set<Marks> markses = new HashSet<Marks>(0);
	private Set<Divison> divisons = new HashSet<Divison>(0);

	public Subjects() {
	}

	public Subjects(int id) {
		this.id = id;
	}

	public Subjects(int id, String nameOfSubjects, Set<Marks> markses, Set<Divison> divisons) {
		this.id = id;
		this.nameOfSubjects = nameOfSubjects;
		this.markses = markses;
		this.divisons = divisons;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nameOfSubjects", length = 50)
	public String getNameOfSubjects() {
		return this.nameOfSubjects;
	}

	public void setNameOfSubjects(String nameOfSubjects) {
		this.nameOfSubjects = nameOfSubjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjects")
	public Set<Marks> getMarkses() {
		return this.markses;
	}

	public void setMarkses(Set<Marks> markses) {
		this.markses = markses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjects")
	public Set<Divison> getDivisons() {
		return this.divisons;
	}

	public void setDivisons(Set<Divison> divisons) {
		this.divisons = divisons;
	}

}
